### ISSUE TITLE
A bug when test MvP in Campus dataset

### ISSUE THREAD

**Issue by Taylorminer** [openxrlab/xrmocap#58] opened 2022-12-09 07:36 UTC
When I test MvP in Campus dataset. I run the following command:
![image](https://user-images.githubusercontent.com/41726592/206649221-2d4d4b58-0b39-4f6e-915e-91dc990af20e.png)
And I meet the following error:
![image](https://user-images.githubusercontent.com/41726592/206649632-a48657e3-271c-4b97-b3e9-221ee5d2fe0b.png)
Can you help me?

**Comment by wqyin** [comment] 2022-12-15 08:32
Hello, this might be caused by an empty frame in the input 3D keypoints data. You may try to skip the empty frame by adding `if kps3d_frame.shape[0] == 0: continue` before [this line](https://github.com/openxrlab/xrmocap/blob/main/xrmocap/transform/keypoints3d/optim/rm_duplicate.py#L83). We will fix this bug in the next version as well. Thanks for the feedback.

**Comment by Taylorminer** [comment] 2022-12-16 03:06
> Hello, this might be caused by an empty frame in the input 3D keypoints data. You may try to skip the empty frame by adding `if kps3d_frame.shape[0] == 0: continue` before [this line](https://github.com/openxrlab/xrmocap/blob/main/xrmocap/transform/keypoints3d/optim/rm_duplicate.py#L83). We will fix this bug in the next version as well. Thanks for the feedback.

It works ! But I get a bad result like this:
![image](https://user-images.githubusercontent.com/41726592/208011460-4d39d7d7-708a-4744-aef4-072a5fd1cf1d.png)
If I want to test the model in Campus dataset. Is there other parameters needed to be modified in this file orther file ?
![image](https://user-images.githubusercontent.com/41726592/208012898-00078b7e-a6e0-4ed7-9547-0ea92caba476.png)

**Comment by wqyin** [comment] 2022-12-16 04:08
You may need to use the value in this [config for campus training and evaluation](https://github.com/openxrlab/xrmocap/blob/main/configs/mvp/campus_config/mvp_campus.py) while following the format of this [config for estimator](https://github.com/openxrlab/xrmocap/blob/main/configs/modules/core/estimation/mview_mperson_end2end_estimator.py) if you want to test the estimator with campus dataset. The error was caused by extra arguments given, which are needed for the evaluation but not needed for the estimator. 
Alternatively, you may check the quantitative evaluation following [this tutorial](https://github.com/openxrlab/xrmocap/blob/main/docs/en/getting_started.md#learning-based-methods-1) to make sure everything is in the correct configuration.

**Comment by LazyBusyYang** [comment] 2023-01-03 07:27
Issue closed by #59

**Closed by LazyBusyYang** 2023-01-03 07:27 UTC
